author: Chris Williams <chris@bingosnet.co.uk>
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: POE-Component-Server-SimpleContent
no_index: 
  directory: 
    - inc
    - t
requires: 
  CGI: 0
  Carp: 0
  Filesys::Virtual::Plain: 0.07
  HTTP::Request: 0
  HTTP::Response: 0
  MIME::Types: 1.15
  POE: 0.38
  URI::Escape: 3.28
version: 1.03
